input {
  beats {
    port => 5044
  }
}

filter {
  mutate {
    add_field => { "processed_by" => "logstash" }
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    ilm_enabled => true
    ilm_rollover_alias => "ecommerce-logs"
    ilm_pattern => "{now/d}-000001"
    ilm_policy => "ecommerce-logs-policy"
  }
}
