spring:
  application:
    name: catalog-service
  datasource:
    url: ${CATALOG_DATASOURCE_URL:jdbc:mysql://localhost:3306/catalog_db}
    username: ${CATALOG_DATASOURCE_USERNAME:root}
    password: ${CATALOG_DATASOURCE_PASSWORD:12345678}
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    properties:
      hibernate:
        globally_quoted_identifiers: true
    show-sql: ${JPA_SHOW_SQL:false}

server:
  port: ${SERVER_PORT:8083}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka}
