spring:
  application:
    name: order-service
  datasource:
    url: ${ORDER_DATASOURCE_URL:jdbc:mysql://localhost:3306/ecommerce_order}
    username: ${ORDER_DATASOURCE_USERNAME:root}
    password: ${ORDER_DATASOURCE_PASSWORD:12345678}
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    properties:
      hibernate:
        globally_quoted_identifiers: true
    show-sql: ${JPA_SHOW_SQL:false}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

server:
  port: ${SERVER_PORT:8086}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka}

vnpay:
  tmn-code: ${VNPAY_TMN_CODE:V7F802I1}
  hash-secret: ${VNPAY_HASH_SECRET:Z4JS5RHFB2JIZS19NIVUP83OTL0GHB4K}
  url: ${VNPAY_URL:https://sandbox.vnpayment.vn/paymentv2/vpcpay.html}
  return-url: ${VNPAY_RETURN_URL:http://localhost:8080/api/orders/vnpay-return}
