spring:
  config:
    import: classpath:application-common-local.yml
  datasource:
    url: ${AUTH_DATASOURCE_URL:jdbc:mysql://localhost:3307/ecommerce_auth?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true}
